# Generated by Django 5.1.3 on 2024-12-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('decsription', models.TextField(default="Ma'lumot qo'shilmadi.", verbose_name='Tavsifi')),
                ('url', models.CharField(max_length=50, unique=True, verbose_name='Havolasi')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Surati')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['-id'],
            },
        ),
    ]
