# Generated by Django 5.1.3 on 2024-12-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='decsription',
            new_name='description',
        ),
    ]
